[package]
name = "acm-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "acm command line"

[[bin]]
name = "acm"
path = "src/main.rs"

[dependencies]
acm-config.workspace = true
acm-crypto.workspace = true
acm-devices.workspace = true
acm-engine.workspace = true
acm-error.workspace = true
acm-install.workspace = true
acm-portal.workspace = true
acm-signing.workspace = true
acm-storage.workspace = true
acm-types.workspace = true
clap.workspace = true

[dev-dependencies]
acm-crypto.workspace = true
base64.workspace = true
tempfile.workspace = true
