//! Files an Xcode build reads after `apple-cert-manager sync`.
//!
//! `signing.env` uses sigh's variable names. Each lane also gets
//! `Signing.xcconfig` and `ExportOptions.plist`.

use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

use apple_cert_manager_engine::{SyncReport, SyncedProfile};
use apple_cert_manager_error::{Error, Result};
use apple_cert_manager_types::{Platform, SigningType};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WrittenSigning {
    pub env_path: PathBuf,
    pub files: Vec<PathBuf>,
}

pub fn write_signing_files(report: &SyncReport, output_dir: &Path) -> Result<WrittenSigning> {
    let output_dir = absolute(output_dir);
    fs::create_dir_all(&output_dir)?;
    let mut profiles = report.profiles.clone();
    profiles.sort_by(|left, right| {
        (
            &left.bundle_id,
            left.platform.as_str(),
            left.signing.as_match_str(),
        )
            .cmp(&(
                &right.bundle_id,
                right.platform.as_str(),
                right.signing.as_match_str(),
            ))
    });

    let mut env = String::from(
        "# Generated by apple-cert-manager. Source this file or pass it to xcodebuild.\n",
    );
    let mut files = Vec::new();
    for profile in &profiles {
        let profile_path = write_profile(&output_dir, profile)?;
        env.push_str(&env_block(profile, &profile_path));
        let lane = output_dir
            .join(&profile.bundle_id)
            .join(lane_name(profile.signing, profile.platform));
        fs::create_dir_all(&lane)?;
        let xcconfig = lane.join("Signing.xcconfig");
        fs::write(&xcconfig, xcconfig_body(profile))?;
        files.push(xcconfig);
        if let Some(method) = profile.signing.export_method() {
            let export = lane.join("ExportOptions.plist");
            write_export_options(&export, profile, method)?;
            files.push(export);
        }
        files.push(profile_path);
    }
    let env_path = output_dir.join("signing.env");
    fs::write(&env_path, env)?;
    Ok(WrittenSigning { env_path, files })
}

fn write_profile(output_dir: &Path, profile: &SyncedProfile) -> Result<PathBuf> {
    let name = if profile.uuid.is_empty() {
        format!(
            "{}-{}",
            profile.signing.as_match_str(),
            profile.platform.as_str()
        )
    } else {
        profile.uuid.clone()
    };
    let path = output_dir
        .join("profiles")
        .join(format!("{name}.{}", profile_extension(profile.platform)));
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&path, &profile.content)?;
    Ok(path)
}

fn env_block(profile: &SyncedProfile, profile_path: &Path) -> String {
    let prefix = profile
        .signing
        .sigh_prefix(&profile.bundle_id, profile.platform);
    let mut block = String::new();
    block.push_str(&assignment(&prefix, &profile.uuid));
    block.push_str(&assignment(&format!("{prefix}_team-id"), &profile.team_id));
    block.push_str(&assignment(
        &format!("{prefix}_profile-name"),
        &profile.name,
    ));
    block.push_str(&assignment(
        &format!("{prefix}_profile-path"),
        &profile_path.display().to_string(),
    ));
    block.push_str(&assignment(
        &format!("{prefix}_certificate-name"),
        &profile.certificate_name,
    ));
    block
}

fn xcconfig_body(profile: &SyncedProfile) -> String {
    format!(
        "\
DEVELOPMENT_TEAM = {team}
CODE_SIGN_STYLE = Manual
CODE_SIGN_IDENTITY = {identity}
PROVISIONING_PROFILE_SPECIFIER = {specifier}
",
        team = xc_value(&profile.team_id),
        identity = xc_value(&profile.certificate_name),
        specifier = xc_value(&profile.name),
    )
}

fn write_export_options(path: &Path, profile: &SyncedProfile, method: &str) -> Result<()> {
    let mut provisioning = plist::Dictionary::new();
    provisioning.insert(
        profile.bundle_id.clone(),
        plist::Value::String(profile.name.clone()),
    );
    let mut root = plist::Dictionary::new();
    root.insert("method".into(), plist::Value::String(method.to_string()));
    root.insert("signingStyle".into(), plist::Value::String("manual".into()));
    root.insert(
        "teamID".into(),
        plist::Value::String(profile.team_id.clone()),
    );
    root.insert(
        "provisioningProfiles".into(),
        plist::Value::Dictionary(provisioning),
    );
    if !profile.certificate_name.is_empty() {
        root.insert(
            "signingCertificate".into(),
            plist::Value::String(profile.certificate_name.clone()),
        );
    }
    let mut file = fs::File::create(path)?;
    plist::Value::Dictionary(root)
        .to_writer_xml(&mut file)
        .map_err(|err| Error::msg(format!("cannot write {}: {err}", path.display())))?;
    file.write_all(b"\n")?;
    Ok(())
}

fn assignment(key: &str, value: &str) -> String {
    let escaped = value
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace(['\n', '\r'], " ");
    format!("{key}=\"{escaped}\"\n")
}

fn xc_value(value: &str) -> String {
    if value.is_empty()
        || value
            .chars()
            .any(|ch| !(ch.is_ascii_alphanumeric() || matches!(ch, '.' | '_' | '-')))
    {
        format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
    } else {
        value.to_string()
    }
}

pub fn lane_name(signing: SigningType, platform: Platform) -> String {
    if platform == Platform::Ios {
        signing.as_match_str().to_string()
    } else {
        format!("{}_{}", signing.as_match_str(), platform.as_str())
    }
}

pub fn profile_extension(platform: Platform) -> &'static str {
    match platform {
        Platform::Macos | Platform::Catalyst => "provisionprofile",
        Platform::Ios | Platform::Tvos => "mobileprovision",
    }
}

fn absolute(path: &Path) -> PathBuf {
    if path.is_absolute() {
        path.to_path_buf()
    } else {
        std::env::current_dir()
            .map(|cwd| cwd.join(path))
            .unwrap_or_else(|_| path.to_path_buf())
    }
}
