[package]
name = "acm-portal"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "App Store Connect client"

[dependencies]
acm-config.workspace = true
acm-error.workspace = true
base64.workspace = true
chrono.workspace = true
jsonwebtoken.workspace = true
openssl.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
acm-crypto.workspace = true
